/* bahasa-id.js — terminologi UI Bahasa Indonesia untuk HPS Intelligence.
 * Prinsip: istilah procurement/finance/IT yang memiliki makna operasional
 * dipertahankan konsisten melalui glosarium; nilai internal/select tidak diubah.
 * Sumber terminologi mengikuti pendekatan glossary + style-rule DeepL:
 * industry-specific terms, UI terms, acronyms, and terms that should remain untranslated.
 */
(function(){
  'use strict';

  var EXACT = {
    'CONNECTING':'MENGHUBUNGKAN',
    'CACHED':'TERSIMPAN',
    'STALE':'KEDALUWARSA',
    'UNAVAILABLE':'TIDAK TERSEDIA',
    'LIVE':'LANGSUNG',
    'HYBRID':'HIBRIDA',
    'BLOCKED':'DIBLOKIR',
    'READY':'SIAP',
    'DEGRADED':'TERBATAS',
    'NOT READY':'BELUM SIAP',
    'PASS':'LOLOS',
    'FAIL':'GAGAL',
    'WARN':'PERINGATAN',
    'LOCAL':'LOKAL',
    'CLOUD SYNC':'SINKRON CLOUD',
    'CLOUD OFFLINE':'CLOUD TIDAK TERHUBUNG',
    'None':'Tidak Ada',
    'No response':'Tidak ada respons',
    'OK':'OK',
    'Production':'Produksi',
    'Production RC':'Kandidat Rilis Produksi',
    'Save Draft':'Simpan Draf',
    'Submit for Review':'Ajukan untuk Ditinjau',
    'Start Review':'Mulai Peninjauan',
    'Return for Rework':'Kembalikan untuk Perbaikan',
    'Approve HPS':'Setujui HPS',
    'Reject':'Tolak',
    'Lock Approved Version':'Kunci Versi yang Disetujui',
    'Workflow history':'Riwayat Alur Persetujuan',
    'Current Role':'Peran Saat Ini',
    'Evidence Gate':'Gerbang Bukti Pendukung',
    'Persistence':'Penyimpanan',
    'Supabase / RLS':'Supabase / RLS',
    'No workflow action yet.':'Belum ada tindakan alur persetujuan.',
    'Production Readiness Monitor':'Monitor Kesiapan Produksi',
    'Run Checks':'Jalankan Pemeriksaan',
    'Platform':'Platform',
    'Worker build / API version':'Build Worker / versi API',
    'Supabase Auth / tenant backend':'Autentikasi Supabase / backend tenant',
    'Browser security primitives':'Fitur keamanan browser',
    'Governance modules':'Modul tata kelola',
    'Bank Indonesia JISDOR':'JISDOR Bank Indonesia',
    'BPS inflation':'Inflasi BPS',
    'Kemenkeu Kurs Pajak':'Kurs Pajak Kemenkeu',
    'LKPP official catalog status':'Status katalog resmi LKPP',
    'ESDM regulation source':'Sumber regulasi ESDM',
    'Source':'Sumber',
    'Runtime':'Status Runtime',
    'Role':'Peran',
    'Score':'Skor',
    'Grade':'Tingkat',
    'HPS Use':'Penggunaan HPS',
    'Confidence':'Tingkat Keyakinan',
    'Models Used':'Model yang Digunakan',
    'Primary Evidence':'Bukti Utama',
    'Corroborating Evidence':'Bukti Penguat',
    'Reference / document / URL':'Referensi / dokumen / URL',
    'Published Date':'Tanggal Publikasi',
    'Valid Until':'Berlaku Sampai',
    'Reviewer verified':'Diverifikasi Peninjau',
    'Decision':'Keputusan',
    'Pending':'Menunggu',
    'Material':'Material',
    'Context':'Konteks',
    'Reject':'Tolak',
    'APPROVAL READY':'SIAP DISETUJUI',
    'REVIEW REQUIRED':'PERLU PENINJAUAN',
    'Evidence Coverage':'Cakupan Bukti',
    'Component Confidence':'Keyakinan Komponen',
    'Document Evidence Hub':'Pusat Dokumen Bukti Pendukung',
    'Upload Evidence':'Unggah Bukti Pendukung',
    'Upload':'Unggah',
    'Download':'Unduh',
    'Delete':'Hapus',
    'File':'Berkas',
    'Document Type':'Jenis Dokumen',
    'Expiry Date':'Tanggal Kedaluwarsa',
    'Version':'Versi',
    'Status':'Status',
    'Negotiation Intelligence':'Inteligensi Negosiasi',
    'Historical Outcomes':'Hasil Historis',
    'Production health checks not run yet.':'Pemeriksaan kesehatan produksi belum dijalankan.',
    'Sign In':'Masuk',
    'Signing in...':'Sedang masuk...',
    'Signed in successfully.':'Berhasil masuk.',
    'Signed out.':'Berhasil keluar.',
    'Email':'Email',
    'Password':'Kata sandi',
    'Cancel':'Batal',
    'Close':'Tutup',
    'Sync Data':'Sinkronkan Data',
    'Syncing...':'Menyinkronkan...',
    'Synced':'Tersinkron',
    'Save Snapshot':'Simpan Snapshot',
    'Export Audit Dossier':'Ekspor Dossier Audit',
    'Reset HPS':'Reset HPS',
    'Primary cost drivers':'Faktor pendorong biaya utama',
    'Category applicability profile':'Profil penerapan kategori',
    'Foreign Price Normalization & Landed-Cost Scenario':'Normalisasi Harga Valuta Asing & Skenario Biaya Landed',
    'Quantity':'Jumlah',
    'Freight IDR':'Biaya Angkut IDR',
    'Insurance IDR':'Asuransi IDR',
    'Other customs/handling IDR':'Biaya Kepabeanan/Penanganan Lain IDR',
    'Commercial IDR':'Nilai Komersial IDR',
    'Customs Base':'Dasar Kepabeanan',
    'Duty + Import Tax':'Bea Masuk + Pajak Impor',
    'Landed Scenario':'Skenario Biaya Landed',
    'IT Hardware / Perangkat & Equipment':'Perangkat Keras TI / Peralatan',
    'Data Center Equipment / Infrastructure':'Peralatan / Infrastruktur Pusat Data',
    'Barang Lainnya / General Goods':'Barang Lainnya',
    'Software / SaaS / Subscription':'Perangkat Lunak / SaaS / Langganan',
    'Manpower / BPO / Outsourcing':'Tenaga Kerja / BPO / Alih Daya',
    'Data Center / Colocation / Cloud Infrastructure':'Pusat Data / Kolokasi / Infrastruktur Cloud',
    'Logistics / Distribution / Warehousing':'Logistik / Distribusi / Pergudangan',
    'Payment Terminal Rental / Managed Device':'Sewa Terminal Pembayaran / Perangkat Terkelola',
    'Jasa Lainnya / Other Services':'Jasa Lainnya',
    'Professional / Advisory Consulting (output-based)':'Konsultansi Profesional / Advisory (berbasis keluaran)',
    'Resource / Man-day Consulting (resource-based)':'Konsultansi Berbasis Sumber Daya / Hari-Orang',
    'Construction / Civil / MEP / Fit-Out':'Konstruksi / Sipil / MEP / Fit-Out',
    'General Goods':'Barang Umum',
    'Spare Parts / Consumables':'Suku Cadang / Barang Habis Pakai',
    'Office / Facility Equipment':'Peralatan Kantor / Fasilitas',
    'Other Goods':'Barang Lainnya',
    'General Services':'Jasa Umum',
    'Maintenance / Support Service':'Jasa Pemeliharaan / Dukungan',
    'Managed Service':'Layanan Terkelola',
    'Professional Service':'Jasa Profesional',
    'Other Services':'Jasa Lainnya',
    'Management / Strategy Consulting':'Konsultansi Manajemen / Strategi',
    'IT / Technology Consulting':'Konsultansi TI / Teknologi',
    'Audit / Assessment':'Audit / Asesmen',
    'Project / Program Management':'Manajemen Proyek / Program',
    'Research / Study':'Riset / Kajian',
    'Other Professional Consulting':'Konsultansi Profesional Lainnya',
    'Resource-based Consulting':'Konsultansi Berbasis Sumber Daya',
    'Expert / Specialist Man-day':'Hari-Orang Ahli / Spesialis',
    'Project Team / Squad':'Tim Proyek / Squad',
    'Technical Assistance':'Bantuan Teknis',
    'IT Hardware / Equipment Cost Structure':'Struktur Biaya Perangkat Keras TI / Peralatan',
    'Use OEM/principal pricing and landed-cost evidence. General CPI is contextual only.':'Gunakan harga OEM/Principal dan bukti biaya landed. CPI umum hanya bersifat kontekstual.',
    'OEM / Principal Unit Price':'Harga Satuan OEM / Principal',
    'Unit Price (IDR)':'Harga Satuan (IDR)',
    'Rate / Manday':'Tarif / Hari-Orang',
    'Principal/OEM quotation or official price list':'Penawaran Principal/OEM atau daftar harga resmi',
    'Approved specification / BOQ / delivery terms':'Spesifikasi / BOQ / ketentuan pengiriman yang disetujui',
    'Data Center Equipment Cost Structure':'Struktur Biaya Peralatan Pusat Data',
    'Treat infrastructure equipment as landed hardware with installation and support separated.':'Perlakukan peralatan infrastruktur sebagai perangkat keras landed dengan instalasi dan dukungan dipisahkan.',
    'Principal / OEM Equipment Price':'Harga Peralatan Principal / OEM',
    'General Goods Cost Structure':'Struktur Biaya Barang Umum',
    'Use the most specific category benchmark available before a general index.':'Gunakan acuan kategori yang paling spesifik sebelum menggunakan indeks umum.',
    'Primary Goods / Unit Price':'Barang Utama / Harga Satuan',
    'Other Direct Cost':'Biaya Langsung Lainnya',
    'Comparable quotation / principal / distributor price':'Penawaran pembanding / harga Principal / distributor',
    'Specification and quantity':'Spesifikasi dan jumlah',
    'Freight / delivery evidence':'Bukti biaya angkut / pengiriman',
    'BPS CPI only as approved proxy where no specific index exists':'CPI BPS hanya sebagai proksi yang disetujui jika tidak ada indeks yang lebih spesifik',
    'Software / SaaS Cost Structure':'Struktur Biaya Perangkat Lunak / SaaS',
    'Rate per License / Period':'Tarif per Lisensi / Periode',
    'Cloud / Consumption / Platform Usage':'Penggunaan Cloud / Konsumsi / Platform',
    'Internal historical contract / PO / invoice':'Kontrak / PO / invoice historis internal',
    'Manpower / BPO Cost Structure':'Struktur Biaya Tenaga Kerja / BPO',
    'Use wage regulation and role-specific manpower evidence; broad CPI must not replace UMP/UMK/UMSK.':'Gunakan regulasi upah dan bukti tenaga kerja sesuai peran; CPI umum tidak boleh menggantikan UMP/UMK/UMSK.',
    'Base Manpower / Service Rate':'Tarif Dasar Tenaga Kerja / Jasa',
    'Monthly Rate / FTE':'Tarif Bulanan / FTE',
    'Supervisor / Team Lead Cost':'Biaya Supervisor / Team Lead',
    'Tools, Uniform, Device & Operational Cost':'Biaya Peralatan, Seragam, Perangkat & Operasional',
    'Current UMP/UMK/UMSK decree / JDIH':'Keputusan UMP/UMK/UMSK terkini / JDIH',
    'Role salary or internal manpower benchmark':'Gaji sesuai peran atau acuan tenaga kerja internal',
    'Vendor manpower cost breakdown':'Rincian biaya tenaga kerja vendor',
    'Historical BPO contract / invoice':'Kontrak / invoice BPO historis',
    'Data Center / Colocation Cost Structure':'Struktur Biaya Pusat Data / Kolokasi',
    'Separate space, power, cross-connect and SLA charges to prevent double counting.':'Pisahkan biaya ruang, listrik, cross-connect, dan SLA untuk mencegah perhitungan ganda.',
    'Monthly Rate':'Tarif Bulanan',
    'Monthly Rate / Capacity':'Tarif Bulanan / Kapasitas',
    'Cross / Direct Connect MRC':'MRC Cross / Direct Connect',
    'Service Rate':'Tarif Jasa',
    'Provider signed contract / historical invoice / rate card':'Kontrak penyedia yang ditandatangani / invoice historis / rate card',
    'ESDM tariff regulation / power cost-driver evidence':'Regulasi tarif ESDM / bukti faktor biaya listrik',
    'Cross-connect / OTC rate card':'Rate card cross-connect / OTC',
    'Logistics / Distribution Cost Structure':'Struktur Biaya Logistik / Distribusi',
    'Use route, shipment volume and executable carrier evidence. Fuel indices are cost drivers, not direct freight quotes.':'Gunakan bukti rute, volume pengiriman, dan penawaran carrier yang dapat dieksekusi. Indeks bahan bakar adalah faktor biaya, bukan penawaran freight langsung.',
    'Rate / Trip / Shipment':'Tarif / Perjalanan / Pengiriman',
    'Carrier / forwarder quotation or contract rate card':'Penawaran carrier / forwarder atau rate card kontrak',
    'Fuel price / surcharge basis':'Dasar harga bahan bakar / surcharge',
    'Payment Terminal Rental Cost Structure':'Struktur Biaya Sewa Terminal Pembayaran',
    'Separate rental, connectivity, field service, replacement and financing assumptions.':'Pisahkan asumsi sewa, konektivitas, layanan lapangan, penggantian, dan pendanaan.',
    'Vendor Financing Cost':'Biaya Pendanaan Vendor',
    'Vendor rental quotation / historical rental contract':'Penawaran sewa vendor / kontrak sewa historis',
    'OEM terminal purchase or principal price evidence':'Bukti harga pembelian terminal OEM atau harga Principal',
    'Vendor financing basis / tenor / cost of funds':'Dasar pendanaan vendor / tenor / biaya dana',
    'General Services Cost Structure':'Struktur Biaya Jasa Umum',
    'Use service-specific volume, labor and commercial evidence. Avoid generic CPI when a more specific driver exists.':'Gunakan bukti volume, tenaga kerja, dan komersial yang spesifik terhadap jasa. Hindari CPI umum jika tersedia faktor yang lebih spesifik.',
    'Primary Service Charge':'Biaya Jasa Utama',
    'Rate / Unit':'Tarif / Unit',
    'Direct Service Labor':'Tenaga Kerja Jasa Langsung',
    'Operational / Logistics Cost':'Biaya Operasional / Logistik',
    'Service quotation / contract rate card':'Penawaran jasa / rate card kontrak',
    'Role or operational cost evidence':'Bukti biaya sesuai peran atau operasional',
    'Construction / Civil / MEP Cost Structure':'Struktur Biaya Konstruksi / Sipil / MEP',
    'Build from BOQ, material, labor and equipment evidence; general CPI is not a construction price index.':'Bangun dari bukti BOQ, material, tenaga kerja, dan peralatan; CPI umum bukan indeks harga konstruksi.',
    'Approved BOQ, drawings and technical specification':'BOQ, gambar, dan spesifikasi teknis yang disetujui',
    'Current material quotations / internal purchase evidence':'Penawaran material terkini / bukti pembelian internal',
    'UMP/UMK and project labor benchmark':'UMP/UMK dan acuan tenaga kerja proyek',
    'Professional / Advisory Consulting Cost Structure':'Struktur Biaya Konsultansi Profesional / Advisory',
    'Workshop / Interview / Facilitation Cost':'Biaya Workshop / Wawancara / Fasilitasi',
    'Research / Data / Tool / License Cost':'Biaya Riset / Data / Alat / Lisensi',
    'Team composition, role, seniority and effort assumptions':'Asumsi komposisi tim, peran, senioritas, dan effort',
    'Consulting rate card / comparable engagement / internal history':'Rate card konsultansi / engagement pembanding / histori internal',
    'Resource / Man-day Consulting Cost Structure':'Struktur Biaya Konsultansi Berbasis Sumber Daya / Hari-Orang',
    'Resource-based consulting should be calculated from role-specific effort and billing-rate evidence.':'Konsultansi berbasis sumber daya harus dihitung dari effort sesuai peran dan bukti billing rate.',
    'Consultant / Specialist Resource':'Sumber Daya Konsultan / Spesialis',
    'Billing Rate / Manday':'Billing Rate / Hari-Orang',
    'Tool / License / Workspace Cost':'Biaya Alat / Lisensi / Workspace',
    'TOR / SOW and required roles':'TOR / SOW dan peran yang dibutuhkan',
    'Role-specific billing-rate benchmark':'Acuan billing rate sesuai peran',
    'Select evidence source':'Pilih sumber bukti',
    'Primary Evidence':'Bukti Utama',
    'Corroborating Evidence':'Bukti Penguat',
    'Source / Published Date':'Sumber / Tanggal Publikasi',
    'Material-use: Pending Review':'Penggunaan material: Menunggu Peninjauan',
    'Component amount':'Nilai komponen',
    'Evidence-to-Component Mapping':'Pemetaan Bukti ke Komponen',
    'Evidence Coverage':'Cakupan Bukti',
    'Supported Cost':'Biaya yang Didukung Bukti',
    'Total Direct Cost':'Total Biaya Langsung',
    'Approval blocked':'Persetujuan diblokir',
    'Package-level evidence':'Bukti tingkat paket',
    'Document Evidence Hub':'Pusat Dokumen Bukti Pendukung',
    'Private Contract / PO / Invoice / Quotation / BOQ / SOW / Rate Card evidence. SHA-256 duplicate control, reference versioning, validity tracking and safe text extraction.':'Bukti privat berupa Kontrak / PO / Invoice / Penawaran / BOQ / SOW / Rate Card. Dilengkapi kontrol duplikasi SHA-256, versioning referensi, pemantauan masa berlaku, dan ekstraksi teks yang aman.',
    'SUPABASE PRIVATE STORAGE':'PENYIMPANAN PRIVAT SUPABASE',
    'CLOUD BACKEND REQUIRED':'BACKEND CLOUD WAJIB',
    'Issue / Source Date':'Tanggal Dokumen / Sumber',
    'Hash, Extract & Upload':'Hash, Ekstrak & Unggah',
    'Linked evidence documents':'Dokumen bukti yang ditautkan',
    'Official FX/date normalization and transparent landed-cost scenario. JISDOR = commercial USD reference; BI non-USD reference = non-USD normalization; Kemenkeu Kurs Pajak = customs/tax conversion.':'Normalisasi kurs/tanggal resmi dan skenario biaya landed yang transparan. JISDOR = referensi komersial USD; referensi BI non-USD = normalisasi mata uang non-USD; Kurs Pajak Kemenkeu = konversi kepabeanan/pajak.',
    'Historical baseline':'Baseline Historis',
    'No historical date selected':'Belum ada tanggal historis yang dipilih',
    'Governed Learning & Negotiation Intelligence':'Pembelajaran Terkendali & Inteligensi Negosiasi',
    'Learning uses only Manager/Head-approved outcomes from the same category. Recommendations remain human-reviewed decision support.':'Pembelajaran hanya menggunakan hasil pada kategori yang sama yang telah disetujui Manager/Head. Rekomendasi tetap merupakan dukungan keputusan yang ditinjau manusia.',
    'APPROVED OUTCOMES':'HASIL DISETUJUI',
    'Current HPS Gross':'HPS Saat Ini Termasuk Pajak',
    'Historical-Evidence Target':'Target Berbasis Bukti Historis',
    'Reference negotiation range from approved category outcomes':'Rentang referensi negosiasi dari hasil kategori yang telah disetujui',
    'Record Negotiation Outcome':'Catat Hasil Negosiasi',
    'Learning approval queue':'Antrean Persetujuan Pembelajaran',
    'No pending learning outcomes visible to your role.':'Tidak ada hasil pembelajaran yang menunggu dan dapat dilihat oleh peran Anda.',
    'Approve Learning':'Setujui Pembelajaran',
    'Keep Excluded':'Tetap Dikecualikan',
    'PENDING':'MENUNGGU',
    'MATERIAL':'MATERIAL',
    'CONTEXT':'KONTEKS',
    'REJECT':'TOLAK',
    'DRAFT':'DRAF',
    'SUBMITTED':'DIAJUKAN',
    'UNDER_REVIEW':'DALAM PENINJAUAN',
    'REWORK':'PERBAIKAN',
    'APPROVED':'DISETUJUI',
    'REJECTED':'DITOLAK',
    'LOCKED':'DIKUNCI',
    'ARCHIVED':'DIARSIPKAN',
    'PRIMARY':'UTAMA',
    'SUPPORTING':'PENDUKUNG',
    'COST DRIVER':'FAKTOR BIAYA',
    'CONDITIONAL':'BERSYARAT',
    'INFORMATIONAL':'INFORMASIONAL',
    'Procurement User':'Pengguna Pengadaan',
    'Analyst/Senior':'Analis/Senior',
    'Manager':'Manajer',
    'Procurement Head/Admin':'Kepala Pengadaan/Admin',
    'Auditor':'Auditor',
    'No Tenant Access':'Tidak Memiliki Akses Tenant',
    'PRIMARY_PRICE':'HARGA UTAMA',
    'SUPPORTING_PRICE':'HARGA PENDUKUNG',
    'COST_DRIVER':'FAKTOR BIAYA',
    'CONTEXT':'KONTEKS',
    'DISCOVERY_ONLY':'HANYA PENEMUAN',
    'VERIFIED PRIMARY':'UTAMA TERVERIFIKASI',
    'HIGH CONFIDENCE':'KEYAKINAN TINGGI',
    'ACCEPTABLE':'DAPAT DITERIMA',
    'SUPPORTING ONLY':'HANYA PENDUKUNG',
    'USER PROVIDED':'INPUT PENGGUNA',
    'INTERNAL':'INTERNAL'
  };

  var PHRASES = [
    [/Production Readiness Monitor/g,'Monitor Kesiapan Produksi'],
    [/Runtime, backend and official-provider smoke checks\./g,'Pemeriksaan singkat runtime, backend, dan penyedia data resmi.'],
    [/Category-specific evidence applicability remains governed by the HPS engine\./g,'Kesesuaian bukti per kategori tetap dikendalikan oleh mesin HPS.'],
    [/Source Reliability & Evidence Governance/g,'Keandalan Sumber & Tata Kelola Bukti Pendukung'],
    [/Evidence-to-Component/g,'Pemetaan Bukti ke Komponen'],
    [/Evidence to Component/g,'Pemetaan Bukti ke Komponen'],
    [/Approval Workflow & RBAC/g,'Alur Persetujuan & RBAC'],
    [/Maker-checker workflow\./g,'Alur maker-checker.'],
    [/Approved\/locked production versions are immutable/g,'Versi produksi yang telah disetujui\/dikunci bersifat tidak dapat diubah'],
    [/requires server-side Supabase RLS\/RPC enforcement/g,'memerlukan penegakan RLS\/RPC Supabase di sisi server'],
    [/Local preview — production approval disabled/g,'Pratinjau lokal — persetujuan produksi dinonaktifkan'],
    [/Production approval\/lock requires configured Supabase authentication and tenant RLS\./g,'Persetujuan\/penguncian produksi memerlukan autentikasi Supabase dan RLS tenant yang aktif.'],
    [/Submission blocked:/g,'Pengajuan diblokir:'],
    [/Approval blocked:/g,'Persetujuan diblokir:'],
    [/resolve critical evidence gaps/g,'selesaikan kekurangan bukti kritis'],
    [/supported direct cost/g,'biaya langsung yang didukung bukti'],
    [/Your role/g,'Peran Anda'],
    [/cannot perform/g,'tidak dapat melakukan'],
    [/A reason is required/g,'Alasan wajib diisi'],
    [/Reason \/ remediation required/g,'Alasan / perbaikan yang diperlukan'],
    [/Rejection reason/g,'Alasan penolakan'],
    [/Approval note/g,'Catatan persetujuan'],
    [/Workflow transition failed/g,'Transisi alur persetujuan gagal'],
    [/Cloud draft save failed/g,'Penyimpanan draf ke cloud gagal'],
    [/Required \/ Relevant Evidence for This Category/g,'Bukti yang Wajib / Relevan untuk Kategori Ini'],
    [/These are evidence requirements, not automatically verified sources\./g,'Daftar ini adalah kebutuhan bukti, bukan sumber yang otomatis terverifikasi.'],
    [/Only evidence accepted by Source Governance may materially influence the HPS\./g,'Hanya bukti yang diterima oleh Tata Kelola Sumber yang boleh memengaruhi HPS secara material.'],
    [/USER-PROVIDED \/ VERIFIED EVIDENCE ONLY/g,'HANYA INPUT PENGGUNA / BUKTI TERVERIFIKASI'],
    [/PRIMARY BASIS/g,'DASAR UTAMA'],
    [/Direct Non-Labor/g,'Biaya Langsung Non-Tenaga Kerja'],
    [/Direct Labor/g,'Tenaga Kerja Langsung'],
    [/Direct Cost Total/g,'Total Biaya Langsung'],
    [/Subtotal/g,'Subtotal'],
    [/Amount \(IDR\)/g,'Nominal (IDR)'],
    [/Qty/g,'Jumlah'],
    [/Unit Rate \(IDR\)/g,'Tarif Satuan (IDR)'],
    [/Intelligence profile:/g,'Profil inteligensi:'],
    [/Material HPS impact still requires accepted evidence under Source Governance\./g,'Dampak material terhadap HPS tetap memerlukan bukti yang diterima dalam Tata Kelola Sumber.'],
    [/Category-specific drivers will be applied by the calculation engine\./g,'Faktor khusus kategori akan diterapkan oleh mesin perhitungan.'],
    [/profile\)/g,'profil)'],
    [/Cost Build-up/g,'Rincian Biaya'],
    [/Production Evidence/g,'Bukti Pendukung Produksi'],
    [/Vendor Comparison/g,'Perbandingan Vendor'],
    [/Review & Approval/g,'Peninjauan & Persetujuan'],
    [/Outcome Learning/g,'Pembelajaran Hasil'],
    [/Document Evidence/g,'Bukti Dokumen'],
    [/Advanced Intelligence/g,'Inteligensi Lanjutan'],
    [/Governed Learning/g,'Pembelajaran Terkendali'],
    [/Foreign unit amount/g,'Nilai satuan valuta asing'],
    [/Import duty \(%\) — user verified/g,'Bea masuk (%) — diverifikasi pengguna'],
    [/Import VAT\/tax \(%\) — user verified/g,'PPN\/pajak impor (%) — diverifikasi pengguna'],
    [/Apply normalized unit price to primary component/g,'Terapkan harga satuan ternormalisasi ke komponen utama'],
    [/This landed-cost view is a scenario, not a tax ruling\./g,'Tampilan biaya landed ini merupakan skenario, bukan penetapan pajak.'],
    [/Duty\/tax percentages must be verified against DJBC\/Kemenkeu and the correct HS classification\./g,'Persentase bea\/pajak harus diverifikasi terhadap DJBC\/Kemenkeu dan klasifikasi HS yang benar.'],
    [/Freight\/insurance remain explicit to prevent double counting\./g,'Biaya angkut\/asuransi tetap ditampilkan terpisah untuk mencegah perhitungan ganda.'],
    [/Enter a foreign unit amount and retrieve an official current FX rate first\./g,'Masukkan nilai satuan valuta asing dan ambil kurs resmi terkini terlebih dahulu.'],
    [/No primary cost component is defined\./g,'Komponen biaya utama belum ditentukan.'],
    [/Current FX/g,'Kurs Saat Ini'],
    [/Historical FX/g,'Kurs Historis'],
    [/Kurs Pajak/g,'Kurs Pajak'],
    [/Foreign Price/g,'Harga Valuta Asing'],
    [/Commercial/g,'Komersial'],
    [/Historical/g,'Historis'],
    [/Current/g,'Saat Ini'],
    [/Evidence/g,'Bukti Pendukung'],
    [/Governance/g,'Tata Kelola'],
    [/Workflow/g,'Alur Persetujuan'],
    [/Approval/g,'Persetujuan'],
    [/Review/g,'Peninjauan'],
    [/Reviewer/g,'Peninjau'],
    [/Learning/g,'Pembelajaran'],
    [/Negotiation/g,'Negosiasi'],
    [/Document/g,'Dokumen'],
    [/Documents/g,'Dokumen'],
    [/Source/g,'Sumber'],
    [/Sources/g,'Sumber'],
    [/Market Benchmark/g,'Acuan Pasar'],
    [/Historical Escalation/g,'Eskalasi Historis'],
    [/Should-Cost Build-up/g,'Rincian Should-Cost'],
    [/Learning Model/g,'Model Pembelajaran'],
    [/Insufficient Data/g,'Data Tidak Memadai'],
    [/Fresh/g,'Terkini'],
    [/Primary/g,'Utama'],
    [/Supporting/g,'Pendukung'],
    [/Informational/g,'Informasional'],
    [/Rejected/g,'Ditolak'],
    [/Verified/g,'Terverifikasi'],
    [/Verification/g,'Verifikasi'],
    [/Component/g,'Komponen'],
    [/Components/g,'Komponen'],
    [/Category/g,'Kategori'],
    [/Subcategory/g,'Subkategori'],
    [/Pricing Profile/g,'Profil Harga'],
    [/Audit Trail/g,'Jejak Audit'],
    [/Audit trail/g,'Jejak audit'],
    [/Audit/g,'Audit'],
    [/Direct cost/g,'Biaya langsung'],
    [/direct cost/g,'biaya langsung'],
    [/Direct Cost/g,'Biaya Langsung'],
    [/Primary component/g,'Komponen utama'],
    [/primary component/g,'komponen utama'],
    [/Critical/g,'Kritis'],
    [/critical/g,'kritis'],
    [/Coverage/g,'Cakupan'],
    [/Freshness/g,'Kebaruan'],
    [/Authority/g,'Otoritas'],
    [/Price relevance/g,'Relevansi harga'],
    [/Auditability/g,'Keterlacakan audit'],
    [/Independence/g,'Independensi'],
    [/Allowed/g,'Diizinkan'],
    [/Not allowed/g,'Tidak diizinkan'],
    [/Required/g,'Wajib'],
    [/Relevant/g,'Relevan'],
    [/Optional/g,'Opsional'],
    [/Active/g,'Aktif'],
    [/Inactive/g,'Tidak Aktif'],
    [/Created/g,'Dibuat'],
    [/Updated/g,'Diperbarui'],
    [/Uploaded/g,'Diunggah'],
    [/Expired/g,'Kedaluwarsa'],
    [/Expires/g,'Kedaluwarsa'],
    [/Duplicate/g,'Duplikat'],
    [/Extraction/g,'Ekstraksi'],
    [/Extracted/g,'Terekstrak'],
    [/Original/g,'Asli'],
    [/Private/g,'Privat'],
    [/Shared/g,'Bersama'],
    [/Pending approval/g,'Menunggu persetujuan'],
    [/Approved outcome/g,'Hasil yang disetujui'],
    [/Actual cost/g,'Biaya aktual'],
    [/Contract price/g,'Harga kontrak'],
    [/Initial bid/g,'Penawaran awal'],
    [/Target range/g,'Rentang target'],
    [/Discount range/g,'Rentang diskon'],
    [/Median/g,'Median'],
    [/Minimum/g,'Minimum'],
    [/Maximum/g,'Maksimum'],
    [/Procurement User/g,'Pengguna Pengadaan'],
    [/Analyst\/Senior/g,'Analis/Senior'],
    [/Procurement Head\/Admin/g,'Kepala Pengadaan/Admin'],
    [/\bManager\b/g,'Manajer'],
    [/No Tenant Access/g,'Tidak Memiliki Akses Tenant'],
    [/Vendor/g,'Vendor'],
    [/Supplier/g,'Penyedia'],
    [/Principal\/OEM/g,'Principal/OEM'],
    [/Rate Card/g,'Rate Card'],
    [/Cloud/g,'Cloud'],
    [/Dataset/g,'Dataset'],
    [/Provider/g,'Penyedia Data'],
    [/Health/g,'Kesehatan'],
    [/Runtime/g,'Runtime'],
    [/Target/g,'Target'],
    [/Range/g,'Rentang']
  ];

  var PLACEHOLDERS = {
    'Live FX':'Kurs terkini',
    'Optional':'Opsional',
    'Comparable 1':'Pembanding 1',
    'Comparable 2':'Pembanding 2',
    'Comparable 3':'Pembanding 3',
    'Vendor 1':'Vendor 1',
    'Vendor 2':'Vendor 2',
    'Amount (IDR)':'Nominal (IDR)',
    'IDR':'IDR'
  };

  function translateText(input){
    var raw=String(input==null?'':input);
    var lead=(raw.match(/^\s*/)||[''])[0], trail=(raw.match(/\s*$/)||[''])[0], core=raw.trim();
    if(!core) return raw;
    if(EXACT[core]) return lead+EXACT[core]+trail;
    var out=core;
    PHRASES.forEach(function(pair){out=out.replace(pair[0],pair[1]);});
    return lead+out+trail;
  }

  function translateNode(node){
    if(!node) return;
    if(node.nodeType===3){
      var p=node.parentElement;
      if(!p || /^(SCRIPT|STYLE|CODE|PRE)$/.test(p.tagName)) return;
      if(p.tagName==='OPTION' && !p.hasAttribute('value')) return;
      var next=translateText(node.nodeValue);
      if(next!==node.nodeValue) node.nodeValue=next;
      return;
    }
    if(node.nodeType!==1) return;
    if(/^(SCRIPT|STYLE|CODE|PRE)$/.test(node.tagName)) return;
    if(node.tagName==='OPTION' && !node.hasAttribute('value')) return;
    ['placeholder','title','aria-label'].forEach(function(attr){
      if(!node.hasAttribute || !node.hasAttribute(attr)) return;
      var old=node.getAttribute(attr)||'';
      var next=PLACEHOLDERS[old]||translateText(old);
      if(next!==old) node.setAttribute(attr,next);
    });
    Array.prototype.slice.call(node.childNodes||[]).forEach(translateNode);
  }

  var nativeAlert=window.alert.bind(window);
  var nativeConfirm=window.confirm.bind(window);
  var nativePrompt=window.prompt.bind(window);
  window.alert=function(msg){return nativeAlert(translateText(msg));};
  window.confirm=function(msg){return nativeConfirm(translateText(msg));};
  window.prompt=function(msg,def){return nativePrompt(translateText(msg),def);};

  function run(){translateNode(document.body);}
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',run);
  else run();

  var observer=new MutationObserver(function(mutations){
    mutations.forEach(function(m){
      if(m.type==='characterData') translateNode(m.target);
      Array.prototype.slice.call(m.addedNodes||[]).forEach(translateNode);
    });
  });
  if(document.documentElement) observer.observe(document.documentElement,{childList:true,subtree:true,characterData:true});

  window.HPSLangID={
    translate:translateText,
    refresh:run,
    glossary:{
      'Owner\'s Estimate':'Harga Perkiraan Sendiri (HPS)',
      'Procurement':'Pengadaan',
      'Evidence':'Bukti Pendukung',
      'Source Governance':'Tata Kelola Sumber',
      'Cost Driver':'Faktor Pendorong Biaya',
      'Benchmark':'Acuan/Pembanding',
      'Principal/OEM':'Principal/OEM',
      'Maker-Checker':'Maker-Checker',
      'RBAC':'RBAC',
      'JISDOR':'JISDOR',
      'Kurs Pajak':'Kurs Pajak',
      'Should-Cost':'Should-Cost'
    }
  };
})();